title: Pratham
author: Prathamesh Manjrekar
email: pratham.manjrekar.95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This page is a work of Prathamesh Manjrekar. He's the best in the world.
theme: minima
# social links
twitter_username: IAmPM95 # DO NOT include the @ character, or else the build will fail!
github_username:  prathamesh-gh # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
