title: Pratham
author: Prathamesh Manjrekar
email: pratham.manjrekar.95@gmail.com
description: >
  This page is a work of Prathamesh Manjrekar. He's the best in the world.
theme: minima

# social links
twitter_username: IAmPM95
github_username:  prathamesh-gh

show_excerpts: true 
